name: Hola Mundo

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Permet activació manual


jobs:
  log-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
            echo "Hola Mundo."
